name: test wrapper action
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test-action
      id: test-action
      uses: SvanBoxel/parameterizable-docker-action-example@58a0f28
      with: 
        alpine-version: 3.6

    - name: validate output
      run: echo ${{steps.test-action.outputs.version}}
