name: test wrapper action
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test-action
      uses: SvanBoxel/parameterizable-docker-action-example@5ac874e11d63a7af0eeb40c9fb2a731683395062
      with: 
        alpine-version: 3.6

    - name: validate output
      run: ${{steps.test-action.outputs.version}}
